### ISSUE TITLE
一些安卓手机端遇到问题

### ISSUE THREAD

**Issue by Hubray** [synctv-org/synctv#114]
设备系统都是安卓14，浏览器是chrome123版本和微软edge122版本，软件版本是v0.4.4，视频源是alilst[v3.33.0]挂的阿里网盘，
以下问题均在两个以上浏览器和厂家的系统上测试过，并且是必定复现那种

1.手机竖屏模式下，播放器右下角按钮显示不全，需要横屏才能点到全屏按钮

2.手机端下，返回键会按下一次，会执行多次

3.手机端下，进入横屏全屏看视频，播放到12-15分钟期间，会自动退出全屏，且循环出现（再次进入全屏后，12-15分后，依然会出现这情况），需要注意，目前这种情况只出现于alist，并且是播放alilst挂的阿里网盘视频源（我尝试播放alist的本地储存视频，但是一直显示重新连接，所以知道是否也会有这种情况）

4.关于手机端的播放器，希望能支持左右侧上下滑动调节亮度的功能

5.希望能消弱播放器左右滑动视频进度的灵敏度，比如我竖屏模式下，我想输入弹幕，然后下滑到弹幕区（正常操作手机下滑，滑动的轨迹会有一定程度倾斜，会导致被识别到部分x轴滑动，整体结果变成了网页下滑加视频快进），会出现视频快进或者快退的情况。

**Comment by catml** [comment]
第3条，同样遇到了，alist挂载阿里云，看电影，一场电影，pc浏览器页面自动退出全屏，5次左右

**Comment by zijiren233** [comment]
> 第3条，同样遇到了，alist挂载阿里云，看电影，一场电影，pc浏览器页面自动退出全屏，5次左右

使用的版本是？

**Comment by catml** [comment]
你好，我是在2024年4月25日9点拉取的最新镜像。版本应该是0.5.1。



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年5月18日(周六) 晚上9:51
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [synctv-org/synctv] 一些安卓手机端遇到问题 (Issue #114)




  
第3条，同样遇到了，alist挂载阿里云，看电影，一场电影，pc浏览器页面自动退出全屏，5次左右
  
使用的版本是？

**Comment by zijiren233** [comment]
> 你好，我是在2024年4月25日9点拉取的最新镜像。版本应该是0.5.1。
> […](#)
> ---原始邮件--- 发件人: ***@***.***&gt; 发送时间: 2024年5月18日(周六) 晚上9:51 收件人: ***@***.***&gt;; 抄送: ***@***.******@***.***&gt;; 主题: Re: [synctv-org/synctv] 一些安卓手机端遇到问题 (Issue #114) 第3条，同样遇到了，alist挂载阿里云，看电影，一场电影，pc浏览器页面自动退出全屏，5次左右 使用的版本是？ — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: ***@***.***&gt;

0.6.1已经修复了此问题

**Comment by catml** [comment]
好嘞，非常感谢！！！
&nbsp;


GL
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2024年5月18日(星期六) 晚上10:00
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [synctv-org/synctv] 一些安卓手机端遇到问题 (Issue #114)














  
你好，我是在2024年4月25日9点拉取的最新镜像。版本应该是0.5.1。
 …
 ---原始邮件--- 发件人: @.&gt; 发送时间: 2024年5月18日(周六) 晚上9:51 收件人: @.&gt;; 抄送: @.@.&gt;; 主题: Re: [synctv-org/synctv] 一些安卓手机端遇到问题 (Issue #114) 第3条，同样遇到了，alist挂载阿里云，看电影，一场电影，pc浏览器页面自动退出全屏，5次左右 使用的版本是？ — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: @.***&gt;
  
0.6.1已经修复了此问题
